### ISSUE TITLE
consider record instantiation as a use of the record

### ISSUE THREAD

**Issue by ianmcorvidae** [venantius/yagni#35] opened 2016-01-12 00:34 UTC
In [a bit of code](https://github.com/cyverse/DE/blob/d3f0dd6b687b80de4621d58f7444790eaed73dad/services/data-info/src/data_info/util/schema.clj#L11) I use `defrecord` to create a new `DocOnly` record type. A few lines below, I create a helper function which calls `(DocOnly. ...)`, instantiating the record. However, `DocOnly` is still detected as unused by yagni.

**Comment by venantius** [comment] 2016-01-12 03:10
What version of Yagni are you using? I just downloaded your project and got it configured and `DocOnly` wasn't reported as unused.

**Comment by ianmcorvidae** [comment] 2016-01-12 17:17
This is with yagni 0.1.4. Note that the problematic bit of code isn't in `master` of the repository, only `dev` and `beta`. Since it's a multi-project repository this won't come up except in the `services/data-info/` directory.

Other versions of possible relevance: lein 2.5.2, java 1.8.0_66. In my ~/.lein/profiles.clj I have lein-exec 0.3.5, eastwood 0.2.2, lein-kibit 0.1.2, lein-set-version 0.4.1, slamhound 1.5.5, meitner 0.1.0, and repetition-hunter 1.0.0. The clojure version was being dragged down by a swank-clojure plugin in project.clj, but it appears the same way when I comment that out and it uses clojure 1.7.0.

**Comment by venantius** [comment] 2016-01-12 18:08
Gotcha, I hadn't been paying attention to the branch (whoops!). I'll give it a shot later this evening.

**Comment by venantius** [comment] 2018-12-13 13:05
I'm closing this issue because the linked code seems to work as expected and the branches don't seem to be easily findable. If this is still an issue please post a reproducable gist and I'll revisit.

**Closed by venantius** 2018-12-13 13:05 UTC
