### ISSUE TITLE
Cider jack-in failing

### ISSUE THREAD

**Issue by AndreaCrotti** [venantius/yagni#45] opened 2018-12-13 10:09 UTC
I get following error trying to jack in with Cider, it's maybe related with cider itself but I guess it's something strange with this project as well that's causing it to break?

````java.lang.IllegalArgumentException: No method in multimethod 'op-handler' for dispatch value: null
 at clojure.lang.MultiFn.getFn (MultiFn.java:156)
    clojure.lang.MultiFn.invoke (MultiFn.java:233)
    cider.nrepl.middleware.util.error_handling$eval7051$fn__7052.invoke (error_handling.clj:162)
    clojure.lang.MultiFn.invoke (MultiFn.java:233)
    cider.nrepl.middleware.out$handle_out.invokeStatic (out.clj:127)
    cider.nrepl.middleware.out$handle_out.invoke (out.clj:126)
    clojure.lang.Var.invoke (Var.java:383)
    cider.nrepl$wrap_out$fn__6286.invoke (nrepl.clj:336)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_pprint$fn__6176.invoke (nrepl.clj:119)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_refresh$fn__6302.invoke (nrepl.clj:382)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_info$fn__6252.invoke (nrepl.clj:236)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_tracker$fn__6350.invoke (nrepl.clj:484)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_trace$fn__6342.invoke (nrepl.clj:466)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_resource$fn__6310.invoke (nrepl.clj:408)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_inspect$fn__6262.invoke (nrepl.clj:255)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_content_type$fn__6186.invoke (nrepl.clj:139)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_profile$fn__6294.invoke (nrepl.clj:345)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_complete$fn__6218.invoke (nrepl.clj:172)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl.middleware.pprint$handle_pprint_fn.invokeStatic (pprint.clj:61)
    cider.nrepl.middleware.pprint$handle_pprint_fn.invoke (pprint.clj:56)
    clojure.lang.Var.invoke (Var.java:383)
    cider.nrepl$wrap_pprint_fn$fn__6166.invoke (nrepl.clj:100)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_classpath$fn__6210.invoke (nrepl.clj:166)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_enlighten$fn__6236.invoke (nrepl.clj:218)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_spec$fn__6318.invoke (nrepl.clj:420)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_macroexpand$fn__6270.invoke (nrepl.clj:295)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_ns$fn__6278.invoke (nrepl.clj:308)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_stacktrace$fn__6326.invoke (nrepl.clj:436)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_undef$fn__6358.invoke (nrepl.clj:495)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_slurp$fn__6194.invoke (nrepl.clj:150)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_version$fn__6366.invoke (nrepl.clj:503)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    cider.nrepl$wrap_apropos$fn__6202.invoke (nrepl.clj:158)
    nrepl.middleware$wrap_conj_descriptor$fn__5603.invoke (middleware.clj:15)
    clojure.tools.nrepl.server$handle_STAR_.invokeStatic (server.clj:19)
    clojure.tools.nrepl.server$handle_STAR_.invoke (server.clj:16)
    clojure.tools.nrepl.server$handle$fn__5664.invoke (server.clj:28)
    clojure.core$binding_conveyor_fn$fn__4676.invoke (core.clj:1938)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    java.lang.Thread.run (Thread.java:748)```

**Comment by venantius** [comment] 2018-12-13 10:19
It's possible, but I'm not seeing anything in that stack trace that suggests Yagni would be responsible. Is this problem only present when Yagni is in your `:plugins` key?

**Comment by venantius** [comment] 2018-12-13 11:56
I'm afraid without more information I can't really help here. I suspect this is a CIDER problem and could be related to some sort of dependency collision with Yagni's dependencies, but I just don't know. I'm going to close this for now because I don't have any clear evidence that suggests that the problem is specific to something in this project.

**Closed by venantius** 2018-12-13 11:56 UTC
